---
- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present 

- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Install postgresql
  apt: pkg=postgresql-{{ postgresql_version }} state=present force=yes

- name: Start postgresql server
  service: name=postgresql state=started enabled=yes

- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}={{ postgis_package_version }}
    - libpq-dev

# based on http://trac.osgeo.org/postgis/wiki/UsersWikiPostGIS21UbuntuPGSQL93Apt

- name: ensure template_postgis database exists
  sudo_user: postgres
  postgresql_db: name=template_postgis state=present
  register: createdb_template_postgis

- name: make template_postgis a template
  sudo_user: postgres
  command: psql -d template_postgis -c "UPDATE pg_database SET datistemplate=true WHERE datname='template_postgis';"
  when: createdb_template_postgis.changed

- name: enable postgis extension 
  sudo_user: postgres
  command: psql -d template_postgis -c "CREATE EXTENSION postgis;"
  when: createdb_template_postgis.changed
